title: Benjinx
description: |
  <a href="/blog.html">Blog</a>

twitter_username: benjinx264
github_username:  benjinx

# Build settings
markdown: kramdown
theme: jekyll-theme-minimal
plugins:
  - jekyll-feed

