title: Benjinx's Development Blog
github_username: Benjinx264
twitter_username: benjinx264
github_username:  benjinx

author: Benjamin Campbell

description: |
  <a href="/blog.html">Blog</a>

# Build settings
markdown: kramdown
theme: jekyll-theme-minimal
google_analytics: UA-180919635-1
plugins:
  - jekyll-feed

include: ['_pages', '_game-engine', '_programming']

collections:
  pages:
    output: true
    permalink: /:title:output_ext
  game-engine:
    output: true
    permalink: /:collection/:title:output_ext
  programming:
    output: true
    permalink: /:collection/:title:output_ext